- pack/NMG.json
updated Ser Horas Redwyne, as per the [Unofficial FAQ](http://www.cardgamedb.com/forums/index.php?/topic/27543-the-unofficial-faq/).
> Ser Horas Redwyne

- pack/Core.json
> Maester Cressen

- pack/TS.json
> True Steel

- pack/AtSK.json
> Harmen Uller + Tower of the Sun

- pack/TtB.json
Hey, I didn't know about <abbr> formatting for keywords! Nice!
> TtB - formatting fixed

- packs.json
> Called to Arms released

- pack/LoCR.json
> Jeyne Westerling

- pack/LoCR.json
Sorry about the change of a number, my bad, i'll try not to do it again =_=
> Ser Gregor's Marauders

- pack/TIMC.json
Could you please manually remove these two cards?
http://thronesdb.com/card/04078
http://thronesdb.com/card/05052
> The God's Eye - removed

- packs.json
Also please run the script to grab card images from CardgameDB!
> There Is My Claim released

- translations/fr/packs.json
> les noms des packs sortis

- translations/fr/pack/Core.json
- translations/fr/types.json
traduction des complots, agendas et titres du Core set.
C'est long en fait!
> debut du Core set

- packs.json
Whoops forgot this important part.
> The Fall of Astapor

- pack/HoT.json
fix https://github.com/Alsciende/thronesdb/issues/160
> Margaery is unique

- pack/HoT.json
> corrected deck-limit for The Spider's Web plot.

- pack/Core.json
- pack/WotN.json
- schema/card_schema.json
fixes  Alsciende/thronesdb#141
> ensure "text" attribute on all cards.

- cycles.json
> Add missing cycle entry for Sands of Dorne

- pack/FotOG.json
https://images-cdn.fantasyflightgames.com/filer_public/b4/35/b43521fa-7fa8-41a2-81c4-6ae591cf4d47/gt26_card_king-in-the-north.png
> Add The King in the North

- cycles.json
- packs.json
- translations/de/cycles.json
- translations/es/cycles.json
- translations/fr/cycles.json
> renames draft cycle to variants.

- README.md
- cycles.json
- packs.json
- schema/cycle_schema.json
- schema/pack_schema.json
> removes position attribute for cycles and packs from the schema and data.

- pack/FotS.json
refs throneteki/throneteki-json-data#49
> adds cape wrath.

- pack/FotS.json
refs https://github.com/throneteki/throneteki-json-data/pull/50
> Bara-box Salladhor Saan.

- pack/FotS.json
refs https://github.com/throneteki/throneteki-json-data/pull/51
> adds Lyseni Galley.

- pack/CoW.json
- pack/FotOG.json
- pack/TKP.json
- pack/WotN.json
refs https://github.com/throneteki/throneteki-json-data/pull/60
> emphasize knight trait and fix numerous whitespace issues.

- cycles.json
- packs.json
> creates Premium Packs cycle and moves TTWDFL pack into into.
